export interface ActivityItem {
  id: string;
  title: string;
  description: string;
  image: string;
  category: 'doga' | 'tarih' | 'deneyim' | 'sosyal' | 'yakin';
  location: string;
  transport: 'land' | 'boat';
  boatRoute?: '12adalar' | 'oludeniz_boat';
  isPopular?: boolean;
}

export const ALL_ACTIVITIES: ActivityItem[] = [
  // Doğa & Manzara
  { id: 'oludeniz', title: 'Ölüdeniz', description: 'Dünyanın en iyi plajları listesinden düşmeyen, mavi suları ve platin rengi kumsalları ile ünlü doğa harikası.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', category: 'doga', location: 'Ölüdeniz', transport: 'land', isPopular: true },
  { id: 'kumburnu', title: 'Kumburnu Plajı', description: 'Ölüdeniz\'in durgun lagün noktası. Kano ve deniz bisikleti ile iç kısımları keşfetmek için ideal.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'doga', location: 'Ölüdeniz', transport: 'land' },
  { id: 'belcekiz', title: 'Belcekız Plajı', description: 'Ölüdeniz\'in ana plajı. Efsaneye göre adını kaptanın oğlu Belcekız\'ın hazin aşk hikayesinden almıştır.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'doga', location: 'Ölüdeniz', transport: 'land' },
  { id: 'butterfly', title: 'Kelebekler Vadisi', description: 'Birinci derece doğal sit alanı. Yalnızca denizden ulaşılabilen, el değmemiş bir cennet bahçesi.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'doga', location: 'Faralya', transport: 'boat', boatRoute: 'oludeniz_boat', isPopular: true },
  { id: 'kabak', title: 'Kabak Koyu', description: 'Faralya köyü sınırlarında, gece binlerce yıldızı görebileceğiniz, yeşil ve mavinin kucaklaştığı huzur noktası.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'doga', location: 'Faralya', transport: 'land', isPopular: true },
  { id: 'cennet', title: 'Cennet Koyu', description: 'Faralya\'da kampçılar için en popüler noktalardan biri. Şehir hayatının gürültüsünden tamamen uzak bir inziva köşesi.', image: 'https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800', category: 'doga', location: 'Faralya', transport: 'boat', boatRoute: 'oludeniz_boat' },
  { id: 'soguksu', title: 'Soğuk Su Koyu', description: 'Kayaköy\'den deniz yoluyla ulaşılan, kayaların arasından çıkan tatlı ve soğuk su kaynaklarıyla ünlü koy.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'doga', location: 'Kayaköy', transport: 'boat', boatRoute: 'oludeniz_boat' },
  { id: 'akvaryum', title: 'Akvaryum Koyu', description: 'Berrak suları ile su altı canlılarını izleyebileceğiniz, 12 adalar rotasının en sevilen duraklarından biri.', image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800', category: 'doga', location: 'Fethiye', transport: 'boat', boatRoute: '12adalar' },
  { id: 'gemiler_koyu', title: 'Gemiler Koyu', description: 'Kayaköy\'ün hemen aşağısında yer alan, hem kara hem deniz yoluyla ulaşılabilen antik liman bölgesi.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'doga', location: 'Kayaköy', transport: 'land' },
  { id: 'boncuklu', title: 'Boncuklu Koyu', description: 'Fethiye yarımadasında yer alan, turkuaz rengi ve temizliği ile bilinen butik koylar bölgesinin incisi.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'doga', location: 'Fethiye', transport: 'land' },
  { id: 'katranci', title: 'Katrancı Koyu', description: 'Fethiye\'ye 16 km mesafede, çam ve okaliptüs ağaçları altında hem kamp hem piknik imkanı sunan tabiat parkı.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'doga', location: 'Yanıklar', transport: 'land' },
  { id: 'gunluklu', title: 'Günlüklü Koyu', description: 'Dünyada nadir bulunan sığla (günlük) ağaçlarının kokusuyla çevrili, güneşin ağaçlardan süzüldüğü masalsı koy.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'doga', location: 'Yanıklar', transport: 'land' },
  { id: 'calis', title: 'Çalış Plajı', description: 'Eşsiz gün batımı manzarası ve yazın serinleten rüzgarıyla meşhur, Caretta Caretta kaplumbağalarının uğrak noktası.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'doga', location: 'Çalış', transport: 'land', isPopular: true },
  { id: 'aksazlar', title: 'Aksazlar Koyu', description: 'Fethiye körfezine bakan, sığ denizi ile özellikle çocuklu aileler için güvenli ve huzurlu bir koy.', image: 'https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800', category: 'doga', location: 'Fethiye', transport: 'land' },
  { id: 'inlice', title: 'İnlice Plajı', description: 'Göcek yolu üzerinde, siyah kumu ve tertemiz denizi ile bilinen, yerel halkın da sıkça tercih ettiği doğal plaj.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'doga', location: 'Göcek', transport: 'land' },
  { id: 'saklikent', title: 'Saklıkent Kanyonu', description: '18 km uzunluğunda ve 200 metre yüksekliğindeki dev kanyon. Karaçay\'ın buz gibi sularında yürüme deneyimi.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'doga', location: 'Seydikemer', transport: 'land', isPopular: true },
  { id: 'gizlikent', title: 'Gizlikent Şelalesi', description: 'Saklıkent\'e 500 metre mesafede, tropik bir ormanda yürüyormuş hissi veren saklı bir cennet ve şelale.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'doga', location: 'Seydikemer', transport: 'land' },
  { id: 'yakapark', title: 'Yakapark', description: 'Soğuk su kaynaklarının üzerine kurulmuş, ağaçlarla çevrili, doğa ile iç içe bir restoran ve dinlenme alanı.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'doga', location: 'Yaka', transport: 'land' },
  { id: 'babadag', title: 'Babadağ', description: 'Fethiye\'nin çatısı. 1965 metre rakımı ile dünyanın en popüler yamaç paraşütü noktalarından biri.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', category: 'doga', location: 'Ölüdeniz', transport: 'land', isPopular: true },
  { id: 'mendos', title: 'Mendos Dağı', description: 'Fethiye\'nin arkasında yükselen, endemik bitki türleri ve muazzam körfez manzarası sunan doğa yürüyüşü rotası.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'doga', location: 'Fethiye', transport: 'land' },

  // Tarihi & Antik Yerler
  { id: 'amintas', title: 'Amyntas Mezarları', description: 'Fethiye\'nin simgesi. M.Ö. 4. yüzyıla tarihlenen, kayalıklara oyulmuş görkemli tapınak tipi kral mezarları.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'tarih', location: 'Merkez', transport: 'land', isPopular: true },
  { id: 'telmessos', title: 'Telmessos Antik Kenti', description: 'Işık ülkesinin ilk yerleşim yeri. İsmini Apollon\'un oğlu Telmessos\'tan alan köklü bir Likya kenti.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'tarih', location: 'Merkez', transport: 'land' },
  { id: 'antik_tiyatro', title: 'Antik Tiyatro', description: 'Roma dönemine ait, limanın hemen yanında yer alan ve denize karşı konumlanmış nadir antik sahnelerden biri.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'tarih', location: 'Merkez', transport: 'land' },
  { id: 'kayakoy', title: 'Kayaköy (Hayalet Köy)', description: 'Karmylassos antik kenti üzerine kurulu, mübadele döneminde terk edilmiş taş evleri ile büyüleyici bir açık hava müzesi.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'tarih', location: 'Kayaköy', transport: 'land', isPopular: true },
  { id: 'afkule', title: 'Afkule Manastırı', description: 'Kayaköy yakınlarında, dik kayalıkların yamacına oyulmuş, inziva ve muazzam deniz manzarası sunan manastır kalıntısı.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'tarih', location: 'Kayaköy', transport: 'land' },
  { id: 'tlos', title: 'Tlos Antik Kenti', description: 'Pegasus\'un doğduğu yer olarak bilinen, Akdağlar\'ın eteklerinde kurulmuş en önemli Likya şehirlerinden biri.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'tarih', location: 'Seydikemer', transport: 'land' },
  { id: 'letoon', title: 'Letoon', description: 'Likya birliğinin kutsal merkezi. Leto, Apollo ve Artemis adına yapılmış tapınakları ile UNESCO Miras Listesi\'nde.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'tarih', location: 'Seydikemer', transport: 'land' },
  { id: 'xanthos', title: 'Xanthos', description: 'Likya\'nın başkenti. Bağımsızlıkları için iki kez topluca intihar eden kahraman insanların hüzünlü ve asil şehri.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'tarih', location: 'Seydikemer', transport: 'land' },
  { id: 'pinara', title: 'Pınara', description: 'Babadağ eteklerinde, binlerce kaya mezarının bal peteği gibi işlendiği Likya\'nın asil ve huzurlu antik kenti.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'tarih', location: 'Seydikemer', transport: 'land' },
  { id: 'sidyma', title: 'Sidyma', description: 'Faralya üzerinden ulaşılabilen, dev anıt mezarları ve Roma dönemi kalıntılarıyla doğanın içinde saklı kalmış antik kent.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'tarih', location: 'Seydikemer', transport: 'land' },
  { id: 'gemiler_adasi', title: 'Gemiler Adası', description: 'St. Nicholas Adası olarak da bilinen, Bizans döneminden kalma kiliseleri ve antik tünelleri ile denizden bir tarih hazinesi.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'tarih', location: 'Kayaköy', transport: 'boat', boatRoute: 'oludeniz_boat', isPopular: true },

  // Aktivite & Deneyim
  { id: 'teleferik', title: 'Babadağ Teleferik', description: 'Ölüdeniz manzarasını ayaklarınızın altına seren, 1700, 1800 ve 1900 metre durakları olan modern gökyüzü yolculuğu.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', category: 'deneyim', location: 'Ölüdeniz', transport: 'land' },
  { id: 'paragliding', title: 'Yamaç Paraşütü', description: 'Dünyanın en iyi uçuş rotasında, yaklaşık 30 dakika süren adrenalin dolu bir gökyüzü deneyimi.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', category: 'deneyim', location: 'Ölüdeniz', transport: 'land' },
  { id: 'tekne_turu', title: '12 Adalar Tekne Turu', description: 'Merkez limandan kalkan, Yassıca Adalar, Tersane ve Göcek koylarını kapsayan huzurlu bir deniz günü.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'deneyim', location: 'Merkez Liman', transport: 'boat', boatRoute: '12adalar' },
  { id: 'jeep_safari', title: 'Jeep Safari', description: 'Saklıkent, Tlos ve çamur banyolarını kapsayan, gün boyu eğlence ve macera dolu tozlu bir yolculuk.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'deneyim', location: 'Seydikemer', transport: 'land' },
  { id: 'atv_safari', title: 'ATV Safari', description: 'Kayaköy ve çam ormanları arasındaki parkurlarda adrenalin dolu off-road sürüş deneyimi.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800', category: 'deneyim', location: 'Kayaköy', transport: 'land' },
  { id: 'dalis', title: 'Dalış Turları', description: 'Fethiye körfezinin berrak sularında, antik amforalar ve su altı mağaralarını keşfedeceğiniz bir deneyim.', image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800', category: 'deneyim', location: 'Merkez', transport: 'boat' },
  { id: 'gunbatimi_tekne', title: 'Gün Batımı Tekne Turu', description: 'Fethiye adalar bölgesinde, akşam yemeği eşliğinde denizin ortasında gün batımını izlemek isteyenlere özel.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'deneyim', location: 'Fethiye', transport: 'boat' },
  { id: 'likya_yolu', title: 'Likya Yolu Yürüyüşü', description: 'Fethiye\'den başlayıp Antalya\'ya uzanan 555 km\'lik dünyanın en iyi yürüyüş rotalarından biri.', image: 'https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800', category: 'deneyim', location: 'Tüm Bölge', transport: 'land' },
  { id: 'kano', title: 'Kano & Paddle Board', description: 'Ölüdeniz\'in sessiz kısımlarında ve mağaraların içinde kendi rotanızı çizebileceğiniz su aktivitesi.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'deneyim', location: 'Ölüdeniz', transport: 'boat', boatRoute: 'oludeniz_boat' },
  { id: 'balık_avı', title: 'Balık Avı Turları', description: 'Fethiye açıklarında, usta kaptanlar eşliğinde sabahın erken saatlerinde huzurlu bir av deneyimi.', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', category: 'deneyim', location: 'Fethiye', transport: 'boat' },
  { id: 'at_safari', title: 'At Safari', description: 'Kayaköy\'ün tarihi taş evleri ve çam ormanları arasından geçerek Ölüdeniz manzarasına ulaştığınız sakin bir gezi.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', category: 'deneyim', location: 'Kayaköy', transport: 'land' },

  // Merkez & Sosyal
  { id: 'marina', title: 'Fethiye Marina', description: 'Şehrin en modern yüzü. Kordon boyu yürüyüşleri ve lüks yatların süslediği sahil şeridi.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'sosyal', location: 'Merkez', transport: 'land' },
  { id: 'ece_marina', title: 'Ece Marina', description: 'Uluslararası standartlarda butik bir marina. Gurme restoranları ve şık kafeleriyle sosyal yaşamın merkezi.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'sosyal', location: 'Merkez', transport: 'land' },
  { id: 'paspatur', title: 'Paspatur Çarşısı', description: 'Fethiye\'nin kalbi. Tarihi butikleri, kilim dükkanları ve lokumcularıyla şehrin otantik alışveriş noktası.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'sosyal', location: 'Merkez', transport: 'land', isPopular: true },
  { id: 'balik_pazari', title: 'Balık Pazarı', description: 'Taze balığınızı seçip etrafındaki restoranlarda hemen pişirttirebileceğiniz eşsiz bir gastronomi durağı.', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', category: 'sosyal', location: 'Merkez', transport: 'land' },
  { id: 'beskaza', title: 'Beşkaza Meydanı', description: 'Şehrin ana meydanı. Atatürk heykeli ve devasa ay-yıldızlı amblemi ile etkinliklerin buluşma noktası.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'sosyal', location: 'Merkez', transport: 'land' },
  { id: 'fethi_bey_parki', title: 'Şehit Fethi Bey Parkı', description: 'Türkiye\'nin en büyük rekreasyon alanlarından biri. Devasa oyun parkları, heykeller ve bisiklet yollarıyla dolu.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800', category: 'sosyal', location: 'Merkez', transport: 'land' },

  // Yakın Yerler
  { id: 'gocek_merkez', title: 'Göcek', description: 'Mavi yolculuğun dünya çapındaki adresi. Sessizliği, lüks yat kulüpleri ve butik çarşısıyla yatçılığın kalbi.', image: 'https://images.unsplash.com/photo-1596395817188-466d6a2f3234?w=800', category: 'yakin', location: 'Göcek', transport: 'land' },
  { id: 'kas', title: 'Kaş', description: 'Fethiye\'ye komşu, Begonvillerle süslü sokakları ve masmavi deniziyle ünlü bohem tatil kasabası.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'yakin', location: 'Antalya', transport: 'land' },
  { id: 'kalkan', title: 'Kalkan', description: 'Yamaçlara kurulu taş evleri, şık teras restoranları ve muhteşem manzarasıyla ünlü butik tatil beldesi.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', category: 'yakin', location: 'Antalya', transport: 'land' },
  { id: 'patara', title: 'Patara Plajı & Antik Kenti', description: 'Likya birliğinin başkentliğini yapmış antik kent ve Caretta Carettaların ana üreme alanı olan devasa kumsal.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', category: 'yakin', location: 'Kaş', transport: 'land' },
  { id: 'kaputas', title: 'Kaputaş Plajı', description: 'Kanyon ağzında yer alan, turkuaz rengiyle büyüleyen, dik merdivenleri ile meşhur Türkiye\'nin en fotojenik plajı.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', category: 'yakin', location: 'Kaş', transport: 'land' },
];

export const REGIONS = [
  { id: 'merkez', name: 'Fethiye Merkez', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=800' },
  { id: 'oludeniz', name: 'Ölüdeniz', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800' },
  { id: 'calis', name: 'Çalış', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800' },
  { id: 'hisaronu', name: 'Hisarönü / Ovacık', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800' },
  { id: 'gocek', name: 'Göcek', image: 'https://images.unsplash.com/photo-1596395817188-466d6a2f3234?w=800' },
];
