export interface ActivityItem {
  id: string;
  title: string;
  description: string;
  image: string;
  category: 'doga' | 'tarih' | 'deneyim' | 'sosyal' | 'yakin';
  location: string;
  transport: 'land' | 'boat';
  boatRoute?: '12adalar' | 'oludeniz_boat';
  isPopular?: boolean;
}

export const ALL_ACTIVITIES: ActivityItem[] = [
  // Doğa & Manzara
  { id: 'butterfly', title: 'Kelebekler Vadisi', description: 'Doğa güzelliği ile büyüleyen Kelebekler Vadisi, Fethiye’de gezilecek yerlerin başında gelir. Yalnızca Türkiye’nin değil, dünyanın en güzel bölgelerinden biri olarak anılan Kelebekler Vadisi; el değmemiş bir doğaya sahip. Bu özelliği ile görenleri büyüleyen manzaralar sunar. Özellikle kamp tatili yapmak isteyenler tarafından tercih edilen bölge, günübirlik tekne turları içinde oldukça ideal. Eğer tekne turuna katılmak istemezseniz Kelebekler Vadisi’nde kalmak için belirli bir giriş ücreti ödemeniz gerekir. Birinci derece doğal sit alanı olarak koruma altında bulunan Kelebekler Vadisi; tırmanış, tüplü dalış ve yamaç paraşütü gibi ekstrem sporların da gerçekleştiği bir alan.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Faralya', transport: 'boat', boatRoute: 'oludeniz_boat', isPopular: true },
  { id: 'kayakoy', title: 'Kayaköy', description: 'Kayaköy, Antik Likya uygarlığının en önemli kentlerinden biri olan Karmylassos kalıntıları üzerine kurulmuş bir bölge. Fethiye merkezine yaklaşık olarak 9 km uzaklıkta bulunan Kayaköy, taş evlerden oluşan eski bir şehir. Geçmiş yıllarda Lebessos adı ile anılan Kayaköy, Fethiye’nin köklü tarihini daha yakından tanımak isteyenlere eşsiz bir fırsat sunar. Tarihi bir yer olmasının yanı sıra unutulmaz manzaralar sunması sebebiyle de hem yerli hem yabancı turistler tarafından ilgi görür. Ölüdeniz’e yürüme mesafesinde olması ise özellikle yaz aylarında kalabalık turist gruplarına ev sahipliği yapmasını sağlar.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=75&fm=webp&fit=crop', category: 'tarih', location: 'Kayaköy', transport: 'land', isPopular: true },
  { id: 'oludeniz', title: 'Ölüdeniz', description: 'Platin rengi kumsallarda tatil yapmak isteyenlerin tercihi olan Ölüdeniz, Türkiye’nin en etkileyici kumsallarında ev sahipliği yapmasıyla ünlü. Dünyanın en iyi plajları listesi her year güncellense de Ölüdeniz listedeki yerini hiçbir zaman kaybetmez. Mavi suları ve platin rengi kumları ile dikkat çeken Ölüdeniz sahilleri, huzurlu ve eğlenceli bir tatil fırsatı sunar. Çevrede konaklama imkanı sağlayacağınız çok sayıda otel bulunur. Bunun yanı sıra pansiyon ve kiralık evlerden yana da tercih yapabilir ve böylelikle tatilinizi oldukça konforlu hale getirebilirsiniz.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Ölüdeniz', transport: 'land', isPopular: true },
  { id: 'likya_yolu', title: 'Likya Yolu', description: 'Fethiye’de gezilecek yerlerin arasında bulunan Likya Yolu, günlük spor ihtiyacının kolaylıkla karşılanabileceği bir yer. Tarihin bir gezi yaparken spor aktiviteler gerçekleştirmek isteyenler tarafından tercih edilen Likya Yolu, 555 kilometre uzunluğuna sahip bir yol. Muğla Ovacık bölgesinden başlayan ve Antalya’daki Geyikbayırı Köyü’nde sonlanan Likya Yolu özellikle nisan ve haziran arasında kalabalık turist gruplarının gözdesi haline gelir.', image: 'https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=600&q=75&fm=webp&fit=crop', category: 'deneyim', location: 'Tüm Bölge', transport: 'land' },
  { id: 'kabak', title: 'Kabak Koyu', description: 'Tertemiz denizi ve unutulmaz manzaralar sunan doğası ile görenleri kendine hayran bırakan Kabak Koyu, yaz aylarının en sevilen yerlerinden biri. Fethiye’nin Faralya Köyü sınırları içerisinde bulunan bu koy, büyüleyici bir güzelliğe sahip. Eğer Kabak Koyu’nda konaklamak isterseniz bungalov evleri ya da pansiyonları tercih edebilirsiniz. Özellikle gece saatlerinde binlerce yıldız tarafından çevrelenen gökyüzünün sunduğu eşsiz manzarayı kesinlikle kaçırmamanızı öneririz.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Faralya', transport: 'land', isPopular: true },
  { id: 'paspatur', title: 'Paspatur Çarşısı', description: 'Fethiye’nin kalbi olarak anılan Paspatur Çarşısı; özellikle kilim, deri ve altın gibi ürünlerin satıldığı dükkanları ile dikkat çeker. Bunun yanı sıra lezzeti deneyimlemek ya da sevdiklerinize hediye olarak götürmek için lokum satan dükkanlar ve Fethiye’de yeme içme ihtiyacınız karşılayacağınızı restoranlarda çarşı içerisinde bulunur. Yorulduğunuz durumda soluklanmak için pek çok farklı kafe ve bar da Paspatur Çarşısı içerisinde yer alır. Yılın her mevsimi ayrı güzel olan çarşı, 24 saat açık.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&q=75&fm=webp&fit=crop', category: 'sosyal', location: 'Merkez', transport: 'land', isPopular: true },
  { id: 'katranci', title: 'Katrancı Koyu Tabiat Parkı', description: 'Fethiye’de kamp için en çok tercih edilen koylardan biri olan Katrancı Koyu Tabiat Parkı, denizin keyfini sürmek isteyenlerin ilk tercihlerinden biri. Fethiye merkezine yaklaşık olarak 16 km mesafede yer alır ve kamp yapma ya da denize girme fırsatı sunar. Yeşil ile mavinin kucaklaştığı bir yer olan Katrancı Koyu Tabiat Parkı, hem eğlenceli hem de huzurlu bir tatil yapmak isteyenlerin tercihi. Bu park aynı zamanda şehir hayatının kaotik havasından uzaklaşmanıza yardımcı olur.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Yanıklar', transport: 'land' },
  { id: 'faralya', title: 'Faralya Köyü', description: 'Türkiye’nin en özel bölgelerinden biri olarak anılan Faralya Köyü, 40 kilometrelik bir alana yayılmıştır. Misafirlerine zamanda yolculuk yaptıran ve en güzel tatil yerlerinden biri olarak anılan bu köy, Roma ve Likya kalıntıları ile süslenmiş eşsiz bir konuma sahip. Aynı zamanda Fethiye’ye 25 km ve Dalaman Havalimanına 70 km uzaklıkta bulunan köy Ölüdeniz’e ise yalnızca 10 km uzaklıkta bulunduğu için dikkat çeker.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Faralya', transport: 'land' },
  { id: 'tlos', title: 'Tlos Antik Kenti', description: 'Muğla’nın Seydikemer İlçesi yakınlarında yer alan Tlos Antik Kenti, Fethiye’ye 42 km uzaklıkta bulunur. Bölgenin en yüksek dağı olarak bilinen Ak Dağların batı yamaçlarında başlayan antik yerleşim, Eşen Nehri’nin vadi düzlüğüne kadar ulaşan geniş bir konuma sahip. Savunmaya elverişli dağlık arazi yapısının yanı sıra bugüne dek ev sahipliği yaptığı egemenliklerini izlerini hala taşıyor olmasıyla dikkat çeker.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=75&fm=webp&fit=crop', category: 'tarih', location: 'Seydikemer', transport: 'land' },
  { id: 'telmessos', title: 'Telmessos Antik Kenti', description: 'Muğla’ya bağlı Fethiye ilçesinin tarihteki ilk yerleşim yeri olma özelliğini taşıyan Telmessos Antik Kenti ismini pek çok rivayete göre Apollon’un oğlu Telmessos’tan almış. Tarihçesi ve kökeni ile ilgili pek fazla bilgiye ulaşmak mümkün olmasa da Likya Karia sınırında bir kıyı kenti olduğu bilinir. Akdeniz kıyı şeridinde kurulan ve yerleşimin kesintisiz olarak günümüze kadar gelmesiyle dikkat çeken Telmessos Antik Kenti, turizm açısından da önemli bir nokta.', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=75&fm=webp&fit=crop', category: 'tarih', location: 'Merkez', transport: 'land' },
  { id: 'dalyan_mezarlar', title: 'Dalyan Kaya Mezarları', description: 'Kaunos’lar tarafından yapıldığı bilinen ve muhteşem bir eser olarak anılan Dalyan Kaya Mezarlığı, bölgenin simgelerinden biri haline gelmiş. Denizden ya da karadan ulaşılabilecek olan mezarlıklar tarihin derinliklerine bir yolculuk yapmak isteyenler tarafından tercih edilir. Köklü bir tarihe geçmiş olan ve Perslerin ya da Büyük İskenderun istilası üzerine yarım kaldığı tahmin edilen mezarlar büyüleyici bir mimariye sahip.', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=75&fm=webp&fit=crop', category: 'tarih', location: 'Dalyan', transport: 'land' },
  { id: 'belcekiz', title: 'Belcekız Plajı', description: 'Ölüdeniz’in eşsiz güzellikteki sularına ev sahipliği yapan ve Fethiye merkezi yalnızca 10 km mesafede bulunan plaj, pek çok efsaneye konu olmuş bir güzelliğe sahip. Herhangi bir giriş ücreti vermenize gerek kalmadan girebileceğiniz Belcekız Plajı, Fethiye’de mutlaka görülmesi gereken plajların arasında bulunur. Rivayete göre buradan geçen tekne ve gemilerin su almak için kıyıya çıktıkları Belcekız ile ilgili en çok anlatılan rivayetler arasındadır.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Ölüdeniz', transport: 'land' },
  { id: 'dalaman_cayi', title: 'Dalaman Çayı', description: 'Gölhisar ilçesinin güneyindeki yeşil göl dağlarından doğan Dalaman Çayı; Çameli, Acıpayam, Ortaca ve Dalaman ilçe sınırları çizer ardından Akdeniz’e dökülerek unutulmaz bir manzara yaratır. Akdeniz ve Ege bölgeleri sınırını çizen Dalaman Çayı, kendine ait bitki örtüsü ve görenleri büyüleyen manzarasıyla Fethiye’de mutlaka görülmesi gereken yerler arasında bulunur.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Dalaman', transport: 'land' },
  { id: 'saklikent', title: 'Saklıkent Milli Parkı', description: 'Saklıkent Milli Parkı ya da bilinen adıyla Saklıkent Kanyonu eşen çayının kolu olan Karaçay tarafından oluşturulan bir kanyon. Fethiye’de mutlaka görülmesi gereken yerler arasında bulunan Saklıkent Milli Parkı doğal güzellikler açısından unutulmaz manzaralar sunuyor olması sebebiyle dikkat çekici. 18 km uzunluğa ve 200 m yüksekliğe sahip bir kanyona ev sahipliği yapan Saklıkent Milli Parkı en dar yeri 2 metreye kadar düşmesiyle öne çıkar.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Seydikemer', transport: 'land', isPopular: true },
  { id: 'amintas', title: 'Fethiye Kral Mezarları', description: 'Tarihi ve doğal zenginlikler ile öne çıkan bir tatil lokasyonu olan Fethiye, Kral Mezarları gibi tarihin köklü sayfalarına ev sahipliği yapan yapılarıyla dikkat çeker. Dik yamaçlar üzerine inşa edilmiş yapılar olan ve sivil mimarinin en güzel örnekleri arasında bulunan kral mezarları günümüzde tapınak olarak da anılır. Günümüze ulaşmayı başaran en eski kalıntılar arasında yer almaları, pek çok kişinin ilgisini çeker.', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=75&fm=webp&fit=crop', category: 'tarih', location: 'Merkez', transport: 'land', isPopular: true },
  { id: 'cennet', title: 'Cennet Koyu', description: 'Fethiye’de tatil yaparken ziyaret etmeniz gereken ve denizinin güzelliği ile sizlere eşsiz bir tatil imkanı sunacak olan Cennet Koyu, kamp için en çok tercih edilen koyların arasında bulunur. Merkeze yaklaşık 16 km uzaklıkta yer alan koy; yalnızca denize girmek için değil, kamp yaparak tatilini daha farklı bir deneyime çevirmek isteyenler tarafından da tercih edilir. Yeşil ve mavinin kucaklaştığı, huzurlu ambiyansı ile dikkat çeker.', image: 'https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Faralya', transport: 'boat', boatRoute: 'oludeniz_boat' },
  { id: 'calis', title: 'Çalış Plajı', description: 'Fethiye’de huzurlu bir tatil yapmak istiyor ve doğal güzellikler ile bütün bir yılın yorgunluğunu üzerinizden atmayı talep ediyorsanız mutlaka Çalış Plajı’na da gitmelisiniz. Tertemiz denizi sayesinde her yıl binlerce yerli ve yabancı turist tarafından ziyaret edilir. Özellikle yaz aylarında nüfusunun neredeyse ikiye katlandığını dile getirmek kesinlikle yanlış olmaz.', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Çalış', transport: 'land', isPopular: true },
  { id: 'kumburnu', title: 'Kumburnu Plajı', description: 'Kumburnu Plajı Fethiye’nin en keyifli plajlarından biri olması sebebiyle dikkat çeker. Plaj içerisinde duş, tuvalet ve soyunma kabini gibi olanaklar bulunur. Bunun yanı sıra plaj içerisinde bisiklet ya da kano kiralayabilir böylelikle Ölüdeniz’de unutulmaz bir deneyim yaşamayı mümkün hale getirebilirsiniz. Temiz doğası ve yeşil ile mavinin her tonunu görmeye imkan tanıması, yoğun bir ilgi görür.', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=600&q=75&fm=webp&fit=crop', category: 'doga', location: 'Ölüdeniz', transport: 'land' },
];

export const REGIONS = [
  { id: 'merkez', name: 'Fethiye Merkez', image: 'https://images.unsplash.com/photo-1544833058-e70f9ca25c17?w=600&q=75&fm=webp&fit=crop' },
  { id: 'oludeniz', name: 'Ölüdeniz', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=75&fm=webp&fit=crop' },
  { id: 'calis', name: 'Çalış', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=600&q=75&fm=webp&fit=crop' },
  { id: 'hisaronu', name: 'Hisarönü / Ovacık', image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=75&fm=webp&fit=crop' },
  { id: 'gocek', name: 'Göcek', image: 'https://images.unsplash.com/photo-1596395817188-466d6a2f3234?w=600&q=75&fm=webp&fit=crop' },
];
